<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="urn:ns:cdm:reisinformatie:message:treinbericht:1" targetNamespace="urn:ns:cdm:reisinformatie:message:treinbericht:1">
	<wsdl:types>
		<xsd:schema xmlns:pis="urn:ns:cdm:reisinformatie:data:vi:1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:ns:cdm:reisinformatie:message:treinbericht:1" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">
			<xsd:import schemaLocation="../../datatypes/schema/ri-cdm-vi-trb.xsd" namespace="urn:ns:cdm:reisinformatie:data:vi:1"/>
			<xsd:element name="PushPatroonInformatieTrein">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element ref="pis:ReisInformatieProductPatroonInformatieTrein"/>
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="PushPatroonInformatieTreinRequestMessage">
		<wsdl:part name="PushPatroonInformatieTreinRequestPart" element="tns:PushPatroonInformatieTrein"/>
	</wsdl:message>
	<wsdl:portType name="PushPatroonInformatieTreinPortType">
		<wsdl:operation name="PushPatroonInformatieTrein">
			<wsdl:input message="tns:PushPatroonInformatieTreinRequestMessage"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="PushPatroonInformatieTreinJmsBinding" type="tns:PushPatroonInformatieTreinPortType">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/jms"/>
		<wsdl:operation name="PushPatroonInformatieTrein">
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="PushPatroonInformatieTreinJmsService">
		<wsdl:port name="PushPatroonInformatieTreinJmsPort" binding="tns:PushPatroonInformatieTreinJmsBinding">
			<soap:address location="jms:/topic?destination=jms/PIS_CDM_1_XML&amp;connectionFactory=jms/TCF_PIS_CDM&amp;targetService=PushPatroonInformatieTreinJmsPort"/>
		</wsdl:port>
	</wsdl:service>
	<!-- $Header: /apps/cvs/ara/RPANEW/rpa_spec3/ri-push-vi-stb.wsdl,v 1.1 2014/10/21 12:34:27 rispikap Exp $ -->
</wsdl:definitions>